#!/bin/bash
sudo bash -c 'echo "\$nrconf{kernelhints} = 0;" > /etc/needrestart/conf.d/silence_kernel.conf'
sudo bash -c 'echo "\$nrconf{restart} = 'a';" >> /etc/needrestart/conf.d/silence_kernel.conf'

sudo apt update
sudo apt upgrade -y
# echo '$nrconf{kernelhints} = 0;' | sudo tee /etc/needrestart/conf.d/silence_kernel.conf >/dev/null
sudo apt install apache2 -y
sudo a2enmod rewrite
sudo systemctl restart apache2
sudo apt install mysql-server -y
sudo apt install php php-cli php-common php-curl php-zip php-gd php-mysql php-xml php-mbstring php-json php-intl -y
sudo sed -i 's/memory_limit = -1/memory_limit = 128M/' /etc/php/8.1/cli/php.ini
sudo sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 16M/' /etc/php/8.1/cli/php.ini
sudo systemctl restart apache2
sudo apt install curl
cd /tmp
curl -s https://api.github.com/repos/PrestaShop/PrestaShop/releases/latest | grep "browser_download_url.*zip" | cut -d : -f 2,3 | tr -d \" | wget -qi -
sudo apt install unzip
sudo unzip prestashop_*.zip -d /var/www/prestashop/
sudo chown -R www-data: /var/www/prestashop/
sudo apt  install awscli -y

sudo bash -c 'cat <<EOF > /etc/apache2/sites-available/prestashop.conf
<VirtualHost *:80>
    ServerAdmin admin@$(curl -s http://checkip.amazonaws.com)
    ServerName $(curl -s http://checkip.amazonaws.com)
    DocumentRoot /var/www/prestashop

    <Directory /var/www/prestashop>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/log/apache2/prestashop-error_log
    CustomLog /var/log/apache2/prestashop-access_log common
</VirtualHost>
EOF'
sudo a2ensite prestashop.conf
sudo a2dissite 000-default.conf
sudo systemctl restart apache2
